# Platform
TARGET_BOARD_PLATFORM := msm8974
TARGET_BOARD_PLATFORM_GPU := qcom-adreno330
TARGET_GLOBAL_CFLAGS += -mtune=cortex-a7 -mfpu=neon
TARGET_GLOBAL_CPPFLAGS += -mtune=cortex-a7 -mfpu=neon
BOARD_VENDOR := hardware/asus/Android.mk

# Architecture
ARCH_ARM_HAVE_NEON := true
ARCH_ARM_HAVE_TLS_REGISTER := false
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := krait
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := krait


# Bootloader
TARGET_NO_BOOTLOADER := false
TARGET_BOOTLOADER_BOARD_NAME := MSM8974

# Kernel
#BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_BASE :=
BOARD_KERNEL_PAGESIZE :=
#BOARD_KERNEL_SEPARATED_DT :=
#BOARD_MKBOOTIMG_ARGS :=
#TARGET_NO_KERNEL :=
#USES_UNCOMPRESSED_KERNEL :=
#TARGET_KERNEL_SOURCE :=
TARGET_KERNEL_CONFIG :=

# Partitions
BOARD_CACHE_DEVICE :=
BOARD_CACHE_FILESYSTEM := 
BOARD_CACHE_FILESYSTEM_OPTIONS :=
BOARD_SYSTEM_DEVICE :=
BOARD_SYSTEM_FILESYSTEM :=
BOARD_SYSTEM_FILESYSTEM_OPTIONS :=
BOARD_DATA_DEVICE :=
BOARD_DATA_FILESYSTEM :=
BOARD_DATA_FILESYSTEM_OPTIONS :=

BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE :=
BOARD_RECOVERYIMAGE_PARTITION_SIZE :=
BOARD_SYSTEMIMAGE_PARTITION_SIZE :=
BOARD_CACHEIMAGE_PARTITION_SIZE :=

# Hardware Rendering
TARGET_GPU_PP_CORE :=
USE_OPENGL_RENDERER :=
NUM_FRAMEBUFFER_SURFACE_BUFFERS :=

# Bluetooth
BOARD_HAVE_BLUETOOTH :=
BOARD_HAVE_BLUETOOTH_BCM :=

# Wi-Fi
BOARD_WPA_SUPPLICANT_DRIVER :=
WPA_SUPPLICANT_VERSION :=
BOARD_WPA_SUPPLICANT_PRIVATE_LIB :=
BOARD_HOSTAPD_DRIVER :=
BOARD_HOSTAPD_PRIVATE_LIB :=
BOARD_WLAN_DEVICE :=
BOARD_WLAN_DEVICE_REV :=
WIFI_DRIVER_FW_PATH_PARAM :=
WIFI_DRIVER_FW_PATH_STA :=
WIFI_DRIVER_FW_PATH_AP :=
WIFI_DRIVER_MODULE_NAME :=
WIFI_DRIVER_MODULE_ARG :=
WIFI_DRIVER_MODULE_AP_ARG :=

# Wi-Fi Tethering
BOARD_HAVE_SAMSUNG_WIFI :=
BOARD_LEGACY_NL80211_STA_EVENTS :=
BOARD_NO_APSME_ATTR :=

# Charger
BOARD_CHARGER_ENABLE_SUSPEND :=
BOARD_CHARGING_MODE_BOOTING_LPM :=

# Recovery
BOARD_HAS_LARGE_FILESYSTEM :=
BOARD_SUPPRESS_EMMC_WIPE :=
BOARD_HAS_NO_MISC_PARTITION :=
BOARD_HAS_NO_REAL_SDCARD :=
BOARD_HAS_NO_SELECT_BUTTON :=
TARGET_RECOVERY_PIXEL_FORMAT :=
DEVICE_RESOLUTION :=
HAVE_SELINUX :=
TARGET_USERIMAGES_USE_EXT4 :=
TARGET_RECOVERY_FSTAB :=

# Audio configs
BOARD_USES_GENERIC_AUDIO :=

# Telephony
BOARD_USE_VETH :=
BOARD_SPRD_RIL :=
USE_BOOT_AT_DIAG :=

# Other
DISABLE_DEXPREOPT :=
WITH_DEXPREOPT :=
DONT_DEXPREOPT_PREBUILTS :=

# Don't generate block based zips
BLOCK_BASED_OTA :=

USE_CAMERA_STUB :=
BOARD_USE_LEGACY_TOUCHSCREEN :=
TARGET_USE_CUSTOM_LUN_FILE_PATH :=

# CMHW
BOARD_HARDWARE_CLASS :=
